"""add counselor application model

Revision ID: 001_add_counselor_application
Revises: 
Create Date: 2026-08-18 16:39:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_add_counselor_application'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counselor_applications',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('highest_degree', sa.String(length=255), nullable=False),
    sa.Column('degree_field', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('current_role', sa.String(length=255), nullable=False),
    sa.Column('specializations', sa.Text(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('background_info', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counselor_applications_application_id'), 'counselor_applications', ['application_id'], unique=True)
    op.create_index(op.f('ix_counselor_applications_status'), 'counselor_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counselor_applications_status'), table_name='counselor_applications')
    op.drop_index(op.f('ix_counselor_applications_application_id'), table_name='counselor_applications')
    op.drop_table('counselor_applications')
    # ### end Alembic commands ###
